###############################################
#  This is a YML Archive. Precaution to edit  #
###############################################
---
# Config version node. Unique Config name.
# No reason for edit this.
config-version: 1

# Set it to true, and GreekNetwork won't automatically select player's language, instead of this will use lang placed in config
forceDefaultLang: false

general:
  # Supported languages (English (en_US), Czech (cs_CZ), German (de_DE), Japanese (ja_JP), Russian (ru_RU), Chinese (zh_CN), Indonesian (ina_IND))
  # Language is automatically chosen from minecraft. However 'lang' in config is default language e.g for players with Spanish lang.
  #lang: 'en_US'

  # Plugin Prefix.
  # For color you can use "§" or "&".
  prefix: "§6§lGreek§8Network§r "

  # Server where players go when restarting this server.
  #  Don't use "§" or "&", if you use that, your really stupid.
  fallback_server: "lobby1"

  # Send message to player when join to the server.
  # For color you can use "§" or "&".
  # If you want not send a message put "" only
  server_join_message: "§aWelcome to the §l§6Greek§8Network"

  # Set gamemode player when Join
  # 2 = Adventure
  # 3 = Specter
  # 1 = Creative
  # 0 = Survival
  gamemode: 2

  # Coords where player Teleport to join.
  x: 1
  y: 89
  z: -3
  lobby: "hub"

  # Mysql Credentials
  # Host (IP) - Username (Default = root) - Password (Password of DataBase)
  # Database (Mysql Table) - Server (Name of this Server)
  host: 127.0.0.1
  username: root
  password: "YourPasswordHere"
  database: "MysqlDtabase"
  server: lobby1
...