###############################################
#  This is a YML Archive. Precaution to edit  #
###############################################
---
# Config version node. Unique Config name.
# No reason for edit this.
config-version: 1

general:
  # Plugin Prefix.
  # For color you can use "§" or "&".
  prefix: "§6§lGreek§8Network§r "

  # Server where players go when restarting this server.
  #  Don't use "§" or "&", if you use that, your really stupid.
  fallback_server: "lobby1"

  # Message when player Join to the Server.
  # For color you can use "§" or "&".
  player_name_color: "§6"
  server_join_message: "§aWelcome to the §l§6Greek§8Network"

  # Coords where player Teleport to join.
  x: 0
  y: 100
  z: 0
  lobby: "world"

  # Discord WebHook Support.
  webhook: "https://discord.com/api/webhooks/787154034346819615/SwY-fREJ9hacLkoatmeQQC94SqtjylR5vt--Is7-aMx9-sOVLBkvtfHjFARTKZGklhU3"

  # Mysql Credentials
  # Host (IP) - Username (Default = root) - Password (Password of DataBase)
  # Database (Mysql Table) - Server (Name of this Server)
  host: 127.0.0.1
  username: root
  password: "YourPasswordHere"
  database: "MysqlDtabase"
  server: lobby1
...