<?php
declare(strict_types=1);

namespace zOmArRD\plugin;

use pocketmine\plugin\PluginBase;

class GreekNetwork extends PluginBase
{
    public function onEnable()
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }
}